### ISSUE TITLE
How to use this API

### ISSUE THREAD

**Issue by GMatrixGames** [NukkitX/FakeInventories#2]
Hi,

I got the creation of inventories down, but I can't figure out how to open it to the player, could someone help me!

Thanks.

**Comment by SupremeMortal** [comment]
To add: `player.addWindow(inventory)`
To remove: `player.removeWindow(inventory)`
With removal, you'll want to delay it with a task otherwise it could crash the game or make the UI disappear.

**Comment by GMatrixGames** [comment]
Ok, thanks for the info, wasn't sure where to ask it :)
