### ISSUE TITLE
FakeSlotChangeEvent only works with second click

### ISSUE THREAD

**Issue by LucGamesYT** [NukkitX/FakeInventories#3]
The event of FakeInventories only ever works the second time. And if you hold Shift pressed it always works instantly.

**Comment by GamerDaniel3000** [comment]
@LucGamesYT 
German (cause my bad english): Das ist ein Bug den es seit der 1.12 gibt und der nicht von Nukkit ausgeht sondern vom Client aus....
Es ist momentan auf allen Servern der Fall das die FI rumbuggen wie scheiße.

**Comment by EinBexiii** [comment]
Please close this issue, since 1.14 it is working again.
